version: '3.8'

services:
  # 1. Your Go Application
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # This is how we connect. "db" is the hostname of the service below!
      - DB_HOST=db 
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=imagedb
      # NEW: S3 Configuration (Pointing to our local MinIO)
      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=images-bucket
      - S3_USE_SSL=false
    depends_on:
      - db
      - minio

  # 2. The Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: imagedb
    ports:
      - "5432:5432" # Expose port if you want to check DB with a tool like DBeaver
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # NEW: The "Local AWS S3"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Web UI Port (Like AWS Console)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
  
volumes:
  postgres_data:
  minio_data: